macro(link_openssl TARGET_NAME)
  if(NOT DEFINED CBMPC_OPENSSL_ROOT)
    if(DEFINED ENV{CBMPC_OPENSSL_ROOT})
      set(CBMPC_OPENSSL_ROOT $ENV{CBMPC_OPENSSL_ROOT})
    else()
      set(CBMPC_OPENSSL_ROOT "/usr/local/opt/openssl@3.2.0")
    endif()
  endif()

  if(IS_LINUX)
    set(_cbmpc_openssl_include "${CBMPC_OPENSSL_ROOT}/include")
    set(_cbmpc_openssl_lib "${CBMPC_OPENSSL_ROOT}/lib64/libcrypto.a")
    if(NOT EXISTS "${_cbmpc_openssl_lib}")
      set(_cbmpc_openssl_lib "${CBMPC_OPENSSL_ROOT}/lib/libcrypto.a")
    endif()
  elseif(IS_MACOS)
    set(_cbmpc_openssl_include "${CBMPC_OPENSSL_ROOT}/include")
    set(_cbmpc_openssl_lib "${CBMPC_OPENSSL_ROOT}/lib/libcrypto.a")
  else()
    message(STATUS "link_openssl: skipping (unsupported platform)")
    return()
  endif()

  if(NOT EXISTS "${_cbmpc_openssl_include}" OR NOT EXISTS "${_cbmpc_openssl_lib}")
    message(FATAL_ERROR "OpenSSL not found at ${CBMPC_OPENSSL_ROOT}. Set CBMPC_OPENSSL_ROOT.")
  endif()

  target_include_directories(${TARGET_NAME} PUBLIC "${_cbmpc_openssl_include}")
  target_link_libraries(${TARGET_NAME} PUBLIC "${_cbmpc_openssl_lib}")
endmacro(link_openssl)
